FROM node

ENV TZ=America/Bogota
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN npm --version
#RUN apt update
#RUN apt upgrade -y

#RUN apt install git -y
#RUN apt install npm -y

RUN mkdir lab1
WORKDIR /home/lab1
RUN git clone https://github.com/drox13/SD-lab1.git

WORKDIR /home/lab1/SD-lab1/Milldware
RUN git pull
RUN npm install

EXPOSE 8000
CMD ["node", "app.js"]