FROM node

ENV TZ=America/Bogota
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN npm --version
#RUN apt update
#RUN apt upgrade -y

#RUN apt install git -y
#RUN apt install npm -y

RUN mkdir lab1
WORKDIR /home/lab1
RUN git init
RUN git clone --branch main https://github.com/drox13/SD-lab1.git
RUN git pull origin main

WORKDIR /home/lab1/SD-lab1/Milldware
#RUN apt-get install sshpass -y
RUN npm install

EXPOSE 8000
CMD ["node", "app.js"]